models:

  - name: agg_oper_exp_categories
    description: "Aggregated operating expenditures by category"
    tests:
      - not_null:
          column_name: category
      - not_null:
          column_name: transaction_amt

  - name: agg_indiv_contr_by_cand
    description: "Aggregated contributions by candidate"
    tests:
      - not_null:
          column_name: cand_name
      - not_null:
          column_name: party
      - not_null:
          column_name: total_contributions
      - unique:
          column_name:
            - cand_name
      - accepted_values:
          column_name: cand_office
          values: ['House', 'Senate', 'President']           